spring:
  h2:
    console:
      path: "/console"
      enabled: true
  datasource:
    url: "jdbc:h2:file:./app-db"
    username: "admin"
    password: "12345"
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    properties:
      hibernate:
        globally_quoted_identifiers: true
  flyway:
    user: "admin"
    password: "12345"
    url: "jdbc:h2:file:./app-db"